# Generated by Django 2.2.11 on 2020-05-01 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colleage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('term', models.CharField(choices=[('spring', '1R'), ('summer', '1S'), ('fall', '2R'), ('winter', '2W'), ('inter', 'SC')], max_length=2)),
                ('name', models.CharField(max_length=50, null=True)),
                ('col_cd', models.CharField(max_length=10, null=True)),
                ('campus', models.SmallIntegerField(choices=[('seoul', 1), ('sejong', 2)], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('cour_cd', models.CharField(max_length=10, null=True)),
                ('cls', models.SmallIntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('score', models.SmallIntegerField(null=True)),
                ('complition_type', models.CharField(max_length=10, null=True)),
                ('is_relative', models.SmallIntegerField(null=True)),
                ('is_limited', models.SmallIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('prof_cd', models.IntegerField(null=True, unique=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('lab', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('homepage', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('dept_cd', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('colleage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='kuapi.Colleage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('weekend', models.CharField(choices=[('monday', '월'), ('tuesday', '화'), ('wednesday', '수'), ('thursday', '목'), ('friday', '금'), ('saturday', '토'), ('sunday', '일')], max_length=2)),
                ('time_start', models.SmallIntegerField(null=True)),
                ('time_end', models.SmallIntegerField(null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='kuapi.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='kuapi.Department'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='kuapi.Professor'),
        ),
    ]
